name: sindy-cuda
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - numpy<2
  - scipy
  - scikit-learn
  - matplotlib
  - tqdm
  - ipykernel
  - jupyterlab
  - pytorch=2.4.*
  - pytorch-cuda=12.4
  - tensorboard
  - python-dotenv
  - ffmpeg
  - pip
  - pip:
      - torch-tb-profiler==0.4.3
